# Generated by Django 2.2.8 on 2020-01-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200116_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='design_score',
            field=models.IntegerField(choices=[(1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1)]),
        ),
    ]
