# Generated by Django 2.2.8 on 2020-01-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200116_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content_score',
            field=models.IntegerField(choices=[(1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='usability_score',
            field=models.IntegerField(choices=[(1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1)]),
        ),
    ]
